name = "skvault-web"
compatibility_date = "2025-09-02"
compatibility_flags = ["nodejs_compat"]
main = "@tanstack/react-start/server-entry"

[[d1_databases]]
binding = "DB"
database_name = "skvault-db"
database_id = "fb639fe7-fa5a-4196-bfb7-029e80640a73"
migrations_dir = "./drizzle"

[[r2_buckets]]
binding = "SKILLS_BUCKET"
bucket_name = "skvault-skills"

[[kv_namespaces]]
binding = "CACHE"
id = "59fc0ff98a974dd388dd93269f4db115"

[[routes]]
pattern = "skvault.dev"
custom_domain = true

[vars]
APP_URL = "https://skvault.dev"
